name: actions-s3-cache
author: shonansurvivors
description: This action installs dependencies or builds, and caches them in S3.
inputs:
  s3-bucket:
    required: true
  cache-key:
    required: true
  restore-keys:
    required: false
  paths:
    required: true
  command:
    required: true
  tar-option:
    required: false
    default: --use-compress-program=zstd -cf
  untar-option:
    required: false
    default: --use-compress-program=unzstd -xf
  working-directory:
    required: false
    default: ./
  cache-hit-skip:
    required: false
    default: false
runs:
  using: node20
  main: dist/index.js
  post: dist/post/index.js
branding:
  icon: package
  color: yellow
